@URL = http://localhost:4000/api/hotels

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjFmODU2MDUzYzMwMWZiNzY0Y2JmZCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTc2MzgzMzk0NX0.ZRLD8poAmQhegsdBncuBFc4INYE_8YeF_Db21qoz_Kk

POST {{URL}}/create
# Cookie: token={{TOKEN}}
Content-Type: application/json

{
    "name": "lublin hotel1",
	"type": "hotel1",
	"city": "lublin",
	"addres": "somewhere",
	"distance": "500",
	"title": "Best hotel in the city",
	"desc": "hotel description",
	"cheapestPrice": 100
}

###
PUT {{URL}}/691338ae3c3cbb4123bf3c41
Content-Type: application/json

{
    "cheapestPrice": 123,
    "name": "Lublin hotel1"
}

###
DELETE {{URL}}/6913320af215431fc1b734c7

###
GET {{URL}}/691338ae3c3cbb4123bf3c41

###
GET {{URL}}
